import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
const HERE = dirname(fileURLToPath(import.meta.url)); const STUDY = join(HERE, '..');
const RUN = 'run-20261003T141627Z';
const report = readFileSync(join(STUDY, 'REPORT.md'), 'utf8');
const E = JSON.parse(readFileSync(join(STUDY, 'results', RUN, 'endpoints.json'), 'utf8'));
const W = JSON.parse(readFileSync(join(STUDY, 'results', RUN, 'windows.json'), 'utf8'));
const M = JSON.parse(readFileSync(join(STUDY, 'results', RUN, 'manifest.json'), 'utf8'));
let failed = 0; const check = (n, ok) => { if (!ok) { console.error(`FAIL ${n}`); failed++; } };
check('run pinned', report.includes(RUN) && M.peer_rank_js_sha256.startsWith('6ff4582a0de8') && M.repo_sha.startsWith('9feb784') && report.includes('`6ff4582a0de8'));
check('instrument', E.counters.exceptions === 0 && E.counters.hash_mismatches === 0 && E.voided === 0 && E.not_executable === false && E.threshold === 280 && E.spec_margin === 0.1);
check('E1 13/44 FAIL', E.E1.windows === 44 && E.E1.rollbacks === 13 && E.E1.verdict === 'FAIL' && Math.abs(E.E1.upper95 - 0.428) < 1e-3 && Math.abs(E.E1.per_1000_ticks - 1.03) < 0.01 && E.E1.temporal_rollbacks_same_windows === 40 && report.includes('13 / 44 = 0.295'));
check('E2 16/40 FAIL', E.E2.windows === 40 && E.E2.rollbacks === 16 && E.E2.verdict === 'FAIL' && E.E2.early_fraction === 1 && Math.abs(E.E2.lead_hours_vs_I_median + 17.83) < 0.01 && E.E2.with_disappearance === 0 && E.E2.temporal_rollbacks_same_windows === 34 && report.includes('16 / 40 = 0.400'));
check('floors', E.floors_FL90.pairs === 1554 && E.floors_FL90.binding_over_0_10 === 1003 && E.floors_FL90.over_0_50 === 581 && E.floors_FL90.over_1_00 === 224 && E.floors_FL90.pairs_dropped === 210 && report.includes('1,003 exceed the 10% spec margin') && report.includes('224 exceed 1.00'));
check('rank changed 4/2', E.rank_changed_FL90.null_windows === 4 && E.rank_changed_FL90.null_rollbacks_with_change === 2 && report.includes('only 4 of 44 null windows, and 2 of those rolled back'));
check('FL75 18/22', E.E4_FL75.null.rollbacks === 18 && E.E4_FL75.detection.rollbacks === 22 && report.includes('null 18 / 44; detection 22 / 40'));
const nullRb = W.filter((w) => w.arm === 'FL90' && w.kind === 'null' && w.outcome === 'rollback');
check('11 of 13 at ticks 14/15/37/39', nullRb.filter((w) => [14, 15, 37, 39].includes(w.fire_tick)).length === 11 && report.includes('in 11 of 13 cases'));
const det = W.filter((w) => w.arm === 'FL90' && w.kind === 'detection');
check('detection cross-tab 12/4/22', det.filter((w) => w.outcome === 'rollback' && w.temporal_outcome === 'rollback').length === 12 && det.filter((w) => w.outcome === 'rollback' && w.temporal_outcome !== 'rollback').length === 4 && det.filter((w) => w.outcome === 'hold' && w.temporal_outcome === 'rollback').length === 22);
check('11 of 16 at ticks 14/37', det.filter((w) => w.outcome === 'rollback' && (w.fire_tick === 14 || w.fire_tick === 37)).length === 11 && report.includes('11 of them at the same two ticks'));
const byFile = {}; for (const w of W.filter((x) => x.arm === 'FL90' && x.kind === 'null')) (byFile[w.file] ??= []).push(w);
check('files with 0/4', Object.values(byFile).filter((ws) => ws.every((w) => w.outcome === 'hold')).length === 5);
const fl = (sig) => { const xs = W.filter((w) => w.arm === 'FL90').flatMap((w) => w.pre[sig].margins.filter((m) => m !== null)).sort((a, b) => a - b); return xs[Math.floor(xs.length / 2)]; };
check('median floors', fl('DCGM_FI_DEV_GPU_UTIL') === 1 && fl('DCGM_FI_DEV_MEM_COPY_UTIL') === 1 && Math.abs(fl('DCGM_FI_DEV_SM_CLOCK') - 0.851) < 1e-3 && Math.abs(fl('DCGM_FI_DEV_POWER_USAGE') - 0.591) < 1e-3 && Math.abs(fl('DCGM_FI_DEV_GPU_TEMP') - 0.206) < 1e-3 && Math.abs(fl('DCGM_FI_DEV_MEMORY_TEMP') - 0.078) < 1e-3 && fl('DCGM_FI_DEV_MEM_CLOCK') === 0);
for (const q of ['40, 26, 13', 'The count is 13', 'gap drift under stable roles, I did not name', 'not a refutation of the construction']) check(`quotes ${q.slice(0, 25)}`, report.includes(q));
if (failed) { console.error(`${failed} check(s) failed`); process.exit(1); }
console.log('check_report: all checks passed');
